Module4 task2
htmlacademy-nodejs/829185-typoteka-3 pull request #13
Opened 2021-05-09 15:16 UTC by loosq

2021-05-13 19:49 UTC, Krabaton requested changes

2021-05-13 19:49 UTC, Krabaton commented on src/dataValidators/articlesValidator.js
> +  if (!newArticleKeys || !newArticleKeys.some((key) => articleKeys.includes(key))) {
Не годится. Дать вменяемые названия переменных, чтобы было понятно, что мы чекаем. isExistNewArtices, isExistArticleKeys и т.д.  ну через месяц сидеть разбираться что оно делает. в if только переменные с названиями испольщуем

2021-05-13 19:49 UTC, Krabaton commented on src/dataValidators/articlesValidator.js
> +  if (!newArticleKeys || !newArticleKeys.every((key) => articleKeys.includes(key))) {
Аналогично насчет if, что и выше

2021-05-13 19:49 UTC, Krabaton commented on src/dataValidators/commentsValidator.js
> +  if (!(commentKey in req.body) || !req.body[commentKey].length) {
Аналогично насчет if, что и выше

2021-05-13 19:49 UTC, Krabaton commented on src/service/api/articles.e2e.test.js
> +  test(`When get /api/articles valid request, res code should be 200`, async () => {
А почему все тесты скопом? Сгруппировать по типу. Можно по методам HTTP, можно по роутам, но, чтобы хоть как-то выделить а не искать во всем.

2021-06-20 08:23 UTC, loosq commented on src/dataValidators/articlesValidator.js
> +  if (!newArticleKeys || !newArticleKeys.some((key) => articleKeys.includes(key))) {
поправил

2021-06-20 08:23 UTC, loosq commented on src/dataValidators/articlesValidator.js
> +  if (!newArticleKeys || !newArticleKeys.every((key) => articleKeys.includes(key))) {
поправил

2021-06-20 08:23 UTC, loosq commented on src/dataValidators/commentsValidator.js
> +  if (!(commentKey in req.body) || !req.body[commentKey].length) {
поправил

2021-06-20 08:23 UTC, loosq commented on src/service/api/articles.e2e.test.js
> +  test(`When get /api/articles valid request, res code should be 200`, async () => {
разделил по методам

2021-06-20 13:50 UTC, merged